jobs:
    build:
        container: quay.io/skopeo/stable:v1.18.0
        continue-on-error: true
        runs-on: ubuntu-latest
        steps:
        -   name: checkout
            uses: actions/checkout@v2
        -   name: login
            run: for i in {1..5}; do skopeo login -u ${{ secrets.REGISTERY_USERNAME }} registry.cn-hangzhou.aliyuncs.com -p ${{ secrets.REGISTERY_PASSWORD }} || true; done
        -   name: perpare
            run: dnf install pip3 -y && pip3 install redis pyyaml
        -   name: sync
            run: REDIS_HOST=${{ secrets.REDIS_HOST }} REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} SECRET_ID=${{ secrets.SECRET_ID }} SECRET_KEY=${{ secrets.SECRET_KEY }} python3 sync.py ${{ matrix.syncs }} -v
        strategy:
            matrix:
                syncs:
                - cgr.dev/chainguard/bash                                                                                     chainguard_bash
                - 'docker.elastic.co/elasticsearch/elasticsearch                                                               '
                - 'docker.io/80imike/find-container-process                                                                    '
                - 'docker.io/antrea/antrea-ubuntu                                                                              '
                - 'docker.io/apache/apisix                                                                                     '
                - 'docker.io/apache/rocketmq                                                                                   '
                - 'docker.io/apache/rocketmq-exporter                                                                          '
                - 'docker.io/apache/skywalking-swck                                                                            '
                - 'docker.io/apachepulsar/pulsar-all                                                                           '
                - 'docker.io/aweimeow/sctp-server                                                                              '
                - 'docker.io/bitnami/jmx-exporter                                                                              '
                - 'docker.io/bitnami/kubectl                                                                                   '
                - 'docker.io/bitnami/mongodb                                                                                   '
                - 'docker.io/bitnami/mongodb-exporter                                                                          '
                - 'docker.io/bitnami/rabbitmq                                                                                  '
                - docker.io/burlyluo/kindest                                                                                  burlyluo_kindest
                - docker.io/burlyluo/nettool                                                                                  burlyluo_nettool
                - docker.io/burlyluo/vyos                                                                                     burlyluo_vyos
                - docker.io/calico/cni                                                                                        calico_cni
                - docker.io/calico/kube-controllers                                                                           calico_kube-controllers
                - docker.io/calico/node                                                                                       calico_node
                - 'docker.io/cilium/certgen                                                                                    '
                - 'docker.io/cilium/cilium                                                                                     '
                - 'docker.io/cilium/cilium-ci                                                                                  '
                - 'docker.io/cilium/cilium-envoy                                                                               '
                - 'docker.io/cilium/hubble-export-stdout                                                                       '
                - 'docker.io/cilium/hubble-relay                                                                               '
                - 'docker.io/cilium/hubble-ui                                                                                  '
                - 'docker.io/cilium/hubble-ui-backend                                                                          '
                - 'docker.io/cilium/json-mock                                                                                  '
                - docker.io/cilium/netperf                                                                                    cilium_netperf
                - 'docker.io/cilium/operator                                                                                   '
                - 'docker.io/cilium/operator-generic                                                                           '
                - 'docker.io/cilium/startup-script                                                                             '
                - 'docker.io/cilium/tetragon                                                                                   '
                - 'docker.io/cilium/tetragon-operator                                                                          '
                - 'docker.io/clickhouse/clickhouse-server                                                                      '
                - docker.io/cloudnativelabs/kube-router                                                                       cloudnativelabs_kube-router
                - 'docker.io/curlimages/curl                                                                                   '
                - 'docker.io/docker/dockerfile                                                                                 '
                - docker.io/envoyproxy/envoy                                                                                  envoyproxy_envoy
                - 'docker.io/flannel/flannel                                                                                   '
                - 'docker.io/flannel/flannel-cni-plugin                                                                        '
                - docker.io/flannelcni/flannel                                                                                flannelcni_flannel
                - 'docker.io/flomesh/fsm-bootstrap                                                                             '
                - 'docker.io/flomesh/fsm-controller                                                                            '
                - 'docker.io/flomesh/fsm-curl                                                                                  '
                - 'docker.io/flomesh/fsm-ingress                                                                               '
                - 'docker.io/flomesh/fsm-injector                                                                              '
                - 'docker.io/flomesh/fsm-preinstall                                                                            '
                - 'docker.io/flomesh/fsm-sidecar-init                                                                          '
                - 'docker.io/flomesh/pipy                                                                                      '
                - 'docker.io/flomesh/pipy-repo                                                                                 '
                - 'docker.io/fluent/fluent-bit                                                                                 '
                - 'docker.io/frooodle/s-pdf                                                                                    '
                - 'docker.io/goharbor/harbor-core                                                                              '
                - 'docker.io/goharbor/harbor-db                                                                                '
                - 'docker.io/goharbor/harbor-jobservice                                                                        '
                - 'docker.io/goharbor/harbor-log                                                                               '
                - 'docker.io/goharbor/harbor-portal                                                                            '
                - 'docker.io/goharbor/harbor-registryctl                                                                       '
                - 'docker.io/goharbor/nginx-photon                                                                             '
                - 'docker.io/goharbor/prepare                                                                                  '
                - 'docker.io/goharbor/redis-photon                                                                             '
                - 'docker.io/goharbor/registry-photon                                                                          '
                - 'docker.io/grafana/grafana                                                                                   '
                - 'docker.io/grafana/loki                                                                                      '
                - 'docker.io/istio/examples-bookinfo-details-v1                                                                '
                - 'docker.io/istio/examples-bookinfo-details-v2                                                                '
                - 'docker.io/istio/examples-bookinfo-mongodb                                                                   '
                - 'docker.io/istio/examples-bookinfo-mysqldb                                                                   '
                - 'docker.io/istio/examples-bookinfo-productpage-v1                                                            '
                - 'docker.io/istio/examples-bookinfo-ratings-v1                                                                '
                - 'docker.io/istio/examples-bookinfo-ratings-v2                                                                '
                - 'docker.io/istio/examples-bookinfo-reviews-v1                                                                '
                - 'docker.io/istio/examples-bookinfo-reviews-v2                                                                '
                - 'docker.io/istio/examples-bookinfo-reviews-v3                                                                '
                - 'docker.io/istio/examples-helloworld-v1                                                                      '
                - 'docker.io/istio/examples-helloworld-v2                                                                      '
                - 'docker.io/istio/health                                                                                      '
                - 'docker.io/istio/install-cni                                                                                 '
                - 'docker.io/istio/pilot                                                                                       '
                - 'docker.io/istio/proxyv2                                                                                     '
                - 'docker.io/istio/tcp-echo-server                                                                             '
                - 'docker.io/istio/ztunnel                                                                                     '
                - 'docker.io/jaegertracing/all-in-one                                                                          '
                - 'docker.io/joxit/docker-registry-ui                                                                          '
                - 'docker.io/karmada/karmada-agent                                                                             '
                - 'docker.io/karmada/karmada-aggregated-apiserver                                                              '
            max-parallel: 100
name: sync-0
'on':
    pull_request:
        branches:
        - main
    push:
        branches:
        - main
    schedule:
    -   cron: 0 */1 * * *
