jobs:
    build:
        container: quay.io/skopeo/stable:v1.18.0
        continue-on-error: true
        runs-on: ubuntu-latest
        steps:
        -   name: checkout
            uses: actions/checkout@v2
        -   name: login
            run: for i in {1..5}; do skopeo login -u ${{ secrets.REGISTERY_USERNAME }} registry.cn-hangzhou.aliyuncs.com -p ${{ secrets.REGISTERY_PASSWORD }} || true; done
        -   name: perpare
            run: dnf install pip3 -y && pip3 install redis pyyaml platform
        -   name: sync
            run: REDIS_HOST=${{ secrets.REDIS_HOST }} REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} SECRET_ID=${{ secrets.SECRET_ID }} SECRET_KEY=${{ secrets.SECRET_KEY }} python3 sync.py ${{ matrix.syncs }} -v
        strategy:
            matrix:
                syncs:
                - 'ghcr.io/apache/skywalking-showcase/recommendation-service                                                   '
                - 'ghcr.io/apache/skywalking-showcase/songs-service                                                            '
                - 'ghcr.io/apache/skywalking/oap                                                                               '
                - 'ghcr.io/apache/skywalking/ui                                                                                '
                - 'ghcr.io/dexidp/dex                                                                                          '
                - 'ghcr.io/eunomia-bpf/ecc-x86_64                                                                              '
                - 'ghcr.io/fluxcd/flagger                                                                                      '
                - 'ghcr.io/fluxcd/flagger-loadtester                                                                           '
                - 'ghcr.io/jimmidyson/configmap-reload                                                                         '
                - 'ghcr.io/k-cloud-labs/kinitiras-webhook                                                                      '
                - ghcr.io/k8snetworkplumbingwg/multi-networkpolicy-iptables                                                   k8snetworkplumbingwg_multi-networkpolicy-iptables
                - ghcr.io/k8snetworkplumbingwg/multus-cni                                                                     k8snetworkplumbingwg_multus-cni
                - ghcr.io/k8snetworkplumbingwg/whereabouts                                                                    k8snetworkplumbingwg_whereabouts
                - 'ghcr.io/mellanox/k8s-rdma-shared-dev-plugin                                                                 '
                - 'ghcr.io/prometheus-operator/prometheus-config-reloader                                                      '
                - 'ghcr.io/skyapm/r3                                                                                           '
                - 'ghcr.io/squat/generic-device-plugin                                                                         '
                - 'ghcr.io/stefanprodan/podinfo                                                                                '
                - 'k8s.gcr.io/sig-storage/csi-attacher                                                                         '
                - 'k8s.gcr.io/sig-storage/csi-node-driver-registrar                                                            '
                - 'k8s.gcr.io/sig-storage/csi-provisioner                                                                      '
                - 'k8s.gcr.io/sig-storage/csi-resizer                                                                          '
                - 'k8s.gcr.io/sig-storage/csi-snapshotter                                                                      '
                - 'public.ecr.aws/zinclabs/openobserve                                                                         '
                - 'quay.io/argoproj/argocd                                                                                     '
                - quay.io/brancz/kube-rbac-proxy                                                                              brancz_kube-rbac-proxy
                - 'quay.io/centos/centos                                                                                       '
                - 'quay.io/cephcsi/cephcsi                                                                                     '
                - 'quay.io/cilium/certgen                                                                                      '
                - 'quay.io/cilium/cilium-ci                                                                                    '
                - 'quay.io/cilium/cilium-envoy                                                                                 '
                - 'quay.io/cilium/hubble-export-stdout                                                                         '
                - 'quay.io/cilium/hubble-ui                                                                                    '
                - 'quay.io/cilium/hubble-ui-backend                                                                            '
                - 'quay.io/cilium/json-mock                                                                                    '
                - 'quay.io/cilium/operator                                                                                     '
                - 'quay.io/cilium/operator-generic                                                                             '
                - 'quay.io/cilium/startup-script                                                                               '
                - 'quay.io/cilium/tetragon                                                                                     '
                - 'quay.io/cilium/tetragon-operator                                                                            '
                - quay.io/coreos/etcd                                                                                         quay_coreos_etcd
                - 'quay.io/frrouting/frr                                                                                       '
                - 'quay.io/jetstack/cert-manager-cainjector                                                                    '
                - 'quay.io/jetstack/cert-manager-controller                                                                    '
                - 'quay.io/jetstack/cert-manager-ctl                                                                           '
                - 'quay.io/jetstack/cert-manager-webhook                                                                       '
                - quay.io/kuberay/operator                                                                                    kuberay_operator
                - quay.io/metallb/controller                                                                                  metallb_controller
                - quay.io/metallb/frr-k8s                                                                                     metallb_frr-k8s
                - quay.io/metallb/speaker                                                                                     metallb_speaker
                - quay.io/prometheus-operator/prometheus-config-reloader                                                      quay_prometheus-config-reloader
                - 'quay.io/prometheus-operator/prometheus-operator                                                             '
                - 'quay.io/prometheus/alertmanager                                                                             '
                - 'quay.io/prometheus/blackbox-exporter                                                                        '
                - 'quay.io/prometheus/node-exporter                                                                            '
                - quay.io/prometheus/prometheus                                                                               prometheus_prometheus
                - 'quay.io/prometheuscommunity/elasticsearch-exporter                                                          '
                - 'quay.io/submariner/lighthouse-agent                                                                         '
                - 'quay.io/submariner/lighthouse-coredns                                                                       '
                - 'quay.io/submariner/nettest                                                                                  '
                - 'quay.io/submariner/submariner-gateway                                                                       '
                - 'quay.io/submariner/submariner-operator                                                                      '
                - 'quay.io/submariner/submariner-route-agent                                                                   '
                - 'registry.k8s.io/dns/k8s-dns-node-cache                                                                      '
                - registry.k8s.io/e2e-test-images/agnhost                                                                     e2e-test-images-agnhost
                - 'registry.k8s.io/etcd                                                                                        '
                - 'registry.k8s.io/kube-apiserver                                                                              '
                - 'registry.k8s.io/kube-controller-manager                                                                     '
                - 'registry.k8s.io/kube-state-metrics/kube-state-metrics                                                       '
                - 'registry.k8s.io/lws/lws                                                                                     '
                - 'registry.k8s.io/metrics-server/metrics-server                                                               '
                - 'registry.k8s.io/prometheus-adapter/prometheus-adapter                                                       '
                - 'skywalking.docker.scarf.sh/apache/skywalking-oap-server                                                     '
                - 'skywalking.docker.scarf.sh/apache/skywalking-ui                                                             '
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice                                      docker_microservices-demo-adservice
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice                                    docker_microservices-demo-cartservice
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice                                docker_microservices-demo-checkoutservice
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice                                docker_microservices-demo-currencyservice
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice                                   docker_microservices-demo-emailservice
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend                                       docker_microservices-demo-frontend
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator                                  docker_microservices-demo-loadgenerator
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice                                 docker_microservices-demo-paymentservice
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice                          docker_microservices-demo-productcatalogservice
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice                          docker_microservices-demo-recommendationservice
                - us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice                                docker_microservices-demo-shippingservice
                - 'us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueueviz-backend                                        '
                - 'us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueueviz-frontend                                       '
            max-parallel: 10
name: sync-2
'on':
    pull_request:
        branches:
        - main
    push:
        branches:
        - main
    schedule:
    -   cron: 0 */6 * * *
