jobs:
    build:
        container: quay.io/skopeo/stable:v1.18.0
        continue-on-error: true
        runs-on: ubuntu-latest
        steps:
        -   name: checkout
            uses: actions/checkout@v2
        -   name: login
            run: for i in {1..5}; do skopeo login -u ${{ secrets.REGISTERY_USERNAME }} registry.cn-hangzhou.aliyuncs.com -p ${{ secrets.REGISTERY_PASSWORD }} || true; done
        -   name: perpare
            run: dnf install pip3 -y && pip3 install redis pyyaml platform
        -   name: sync
            run: REDIS_HOST=${{ secrets.REDIS_HOST }} REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} SECRET_ID=${{ secrets.SECRET_ID }} SECRET_KEY=${{ secrets.SECRET_KEY }} python3 sync.py ${{ matrix.syncs }} -v
        strategy:
            matrix:
                syncs:
                - 'docker.io/kubeshark/front                                                                                   '
                - 'docker.io/kubeshark/hub                                                                                     '
                - 'docker.io/kubeshark/worker                                                                                  '
                - 'docker.io/kubeskoop/agent                                                                                   '
                - docker.io/kubeskoop/controller                                                                              kubeskoop_controller
                - 'docker.io/kubezoo/clusterresourcequota                                                                      '
                - 'docker.io/kubezoo/kubezoo                                                                                   '
                - docker.io/labring/calico                                                                                    labring_calico
                - docker.io/labring/flannel                                                                                   labring_flannel
                - docker.io/labring/helm                                                                                      labring_helm
                - 'docker.io/library/alpine                                                                                    '
                - 'docker.io/library/buildpack-deps                                                                            '
                - 'docker.io/library/busybox                                                                                   '
                - 'docker.io/library/debian                                                                                    '
                - 'docker.io/library/golang                                                                                    '
                - 'docker.io/library/mysql                                                                                     '
                - 'docker.io/library/nginx                                                                                     '
                - docker.io/library/node                                                                                      nodejs
                - 'docker.io/library/postgres                                                                                  '
                - 'docker.io/library/python                                                                                    '
                - 'docker.io/library/redis                                                                                     '
                - 'docker.io/library/registry                                                                                  '
                - 'docker.io/library/ubuntu                                                                                    '
                - 'docker.io/loftsh/vcluster                                                                                   '
                - 'docker.io/mccutchen/go-httpbin                                                                              '
                - 'docker.io/meltwater/latency-test                                                                            '
                - 'docker.io/mingrammer/flog                                                                                   '
                - 'docker.io/moby/buildkit                                                                                     '
                - 'docker.io/mydlqclub/dnsutils                                                                                '
                - 'docker.io/opensearchproject/opensearch                                                                      '
                - 'docker.io/opensearchproject/opensearch-dashboards                                                           '
                - 'docker.io/otel/opentelemetry-collector                                                                      '
                - 'docker.io/pivotalrabbitmq/perf-test                                                                         '
                - 'docker.io/projecthami/hami                                                                                  '
                - 'docker.io/prom/mysqld-exporter                                                                              '
                - 'docker.io/prom/prometheus                                                                                   '
                - 'docker.io/prometheuscommunity/postgres-exporter                                                             '
                - 'docker.io/rancher/k3s                                                                                       '
                - 'docker.io/rancher/mirrored-flannelcni-flannel                                                               '
                - 'docker.io/rancher/mirrored-flannelcni-flannel-cni-plugin                                                    '
                - 'docker.io/rayproject/ray                                                                                    '
                - 'docker.io/redroid/redroid                                                                                   '
                - 'docker.io/rmohr/activemq                                                                                    '
                - docker.io/soelvkaer/vppcontainer                                                                            soelvkaer_vppcontainer
                - 'docker.io/tinygo/tinygo                                                                                     '
                - 'docker.io/traefik/whoami                                                                                    '
                - 'docker.io/vllm/vllm-openai                                                                                  '
                - 'docker.io/volcanosh/dist-mnist-tf-example                                                                   '
                - 'docker.io/volcanosh/vc-controller-manager                                                                   '
                - 'docker.io/volcanosh/vc-scheduler                                                                            '
                - 'docker.io/volcanosh/vc-webhook-manager                                                                      '
                - 'docker.io/wagoodman/dive                                                                                    '
                - 'docker.io/yanbaru/vyos-1.4                                                                                  '
                - 'docker.io/yunwei37/ebpm                                                                                     '
                - gcr.io/google-samples/microservices-demo/adservice                                                          gcr_microservices-demo-adservice
                - gcr.io/google-samples/microservices-demo/cartservice                                                        gcr_microservices-demo-cartservice
                - gcr.io/google-samples/microservices-demo/checkoutservice                                                    gcr_microservices-demo-checkoutservice
                - gcr.io/google-samples/microservices-demo/currencyservice                                                    gcr_microservices-demo-currencyservice
                - gcr.io/google-samples/microservices-demo/emailservice                                                       gcr_microservices-demo-emailservice
                - gcr.io/google-samples/microservices-demo/frontend                                                           gcr_microservices-demo-frontend
                - gcr.io/google-samples/microservices-demo/loadgenerator                                                      gcr_microservices-demo-loadgenerator
                - gcr.io/google-samples/microservices-demo/paymentservice                                                     gcr_microservices-demo-paymentservice
                - gcr.io/google-samples/microservices-demo/productcatalogservice                                              gcr_microservices-demo-productcatalogservice
                - gcr.io/google-samples/microservices-demo/recommendationservice                                              gcr_microservices-demo-recommendationservice
                - gcr.io/google-samples/microservices-demo/shippingservice                                                    gcr_microservices-demo-shippingservice
                - 'gcr.io/heptio-images/ks-guestbook-demo                                                                      '
                - gcr.io/knative-releases/knative.dev/net-istio/cmd/controller                                                net-istio-controller
                - gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook                                                   net-istio-webhook
                - gcr.io/knative-releases/knative.dev/net-kourier/cmd/kourier                                                 net-kourier-kourier
                - gcr.io/knative-releases/knative.dev/serving/cmd/activator                                                   knative-serving-activator
                - gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler                                                  knative-serving-autoscaler
                - gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa                                              knative-serving-autoscaler-hpa
                - gcr.io/knative-releases/knative.dev/serving/cmd/controller                                                  knative-serving-controller
                - gcr.io/knative-releases/knative.dev/serving/cmd/default-domain                                              knative-serving-default-domain
                - gcr.io/knative-releases/knative.dev/serving/cmd/queue                                                       knative-serving-queue
                - gcr.io/knative-releases/knative.dev/serving/cmd/webhook                                                     knative-serving-webhook
                - 'gcr.io/kubebuilder/kube-rbac-proxy                                                                          '
                - gcr.io/kubernetes-e2e-test-images/echoserver                                                                gcr_echoserver
                - 'ghcr.io/apache/skywalking-cli/skywalking-cli                                                                '
                - 'ghcr.io/apache/skywalking-kubernetes-event-exporter/skywalking-kubernetes-event-exporter                    '
                - 'ghcr.io/apache/skywalking-rover/skywalking-rover                                                            '
                - 'ghcr.io/apache/skywalking-satellite/skywalking-satellite                                                    '
                - 'ghcr.io/apache/skywalking-showcase/app                                                                      '
                - 'ghcr.io/apache/skywalking-showcase/frontend                                                                 '
                - 'ghcr.io/apache/skywalking-showcase/gateway-service                                                          '
                - 'ghcr.io/apache/skywalking-showcase/load-gen                                                                 '
                - 'ghcr.io/apache/skywalking-showcase/rating-service                                                           '
            max-parallel: 10
name: sync-1
'on':
    pull_request:
        branches:
        - main
    push:
        branches:
        - main
    schedule:
    -   cron: 0 */6 * * *
